import type { Program, RadioStation, PodcastCategory, MediaCategory } from "./types";

export const MEDIA_CATEGORIES: MediaCategory[] = [
  { id: "quran",   label: "تفسير القرآن",  icon: "📖", color: "#10b981" },
  { id: "dawah",   label: "دعوية وإيمانية", icon: "🎙️", color: "#8b5cf6" },
  { id: "fatwa",   label: "فتاوى وأحكام",   icon: "⚖️", color: "#f59e0b" },
  { id: "stories", label: "قصص وسيرة",      icon: "📜", color: "#ef4444" },
  { id: "radio",   label: "إذاعية",         icon: "📻", color: "#3b82f6" },
];

export const PROGRAMS: Program[] = [
  { id: "p1",  name: "لعلهم يفقهون",      host: "د. عمر عبد الكافي",     category: "quran",  featured: true, hot: true, badge: "الأشهر",  color: "#064e3b", colorTo: "#065f46", icon: "📖" },
  { id: "p2",  name: "في رحاب سورة",       host: "د. راغب السرجاني",       category: "quran",  featured: true,                              color: "#065f46", colorTo: "#047857", icon: "🌿" },
  { id: "p3",  name: "خواطر",              host: "أحمد الشقيري",           category: "quran",  featured: true, hot: true, badge: "تريند",   color: "#1e3a5f", colorTo: "#1e40af", icon: "✨" },
  { id: "p4",  name: "تفسير الشعراوي",     host: "الشيخ الشعراوي",         category: "quran",  featured: true,            badge: "أيقونة",  color: "#3b0764", colorTo: "#6d28d9", icon: "📜" },
  { id: "p5",  name: "نور على نور",        category: "quran",                                                                                color: "#166534", colorTo: "#15803d", icon: "💡" },
  { id: "p6",  name: "بينات",              category: "quran",                                                                                color: "#1e3a5f", colorTo: "#1d4ed8", icon: "🔆" },
  { id: "p7",  name: "القرآن علم وعمل",    category: "quran",                                                                                color: "#422006", colorTo: "#92400e", icon: "🧠" },
  { id: "p8",  name: "مع القرآن",          category: "quran",                                                                                color: "#14532d", colorTo: "#166534", icon: "🌙" },
  { id: "p9",  name: "آيات بينات",         category: "quran",                                                                                color: "#1c1917", colorTo: "#292524", icon: "🌟" },
  { id: "p10", name: "ورتل القرآن ترتيلا", category: "quran",                                                                                color: "#0c4a6e", colorTo: "#0369a1", icon: "🎵" },

  { id: "p11", name: "سواعد الإخاء",       host: "نخبة دعاة",              category: "dawah",  featured: true, hot: true, badge: "ملتهب",   color: "#7c2d12", colorTo: "#b45309", icon: "🤝" },
  { id: "p12", name: "الحصن",              category: "dawah",                                                                                color: "#1e3a8a", colorTo: "#1d4ed8", icon: "🏰" },
  { id: "p13", name: "قلوب عامرة",         category: "dawah",                                                                                color: "#4a1942", colorTo: "#7c3aed", icon: "❤️" },
  { id: "p14", name: "يحب الجمال",         category: "dawah",                                                                                color: "#0f172a", colorTo: "#1e293b", icon: "🌸" },
  { id: "p15", name: "الإمام الطيب",       host: "شيخ الأزهر",             category: "dawah",  featured: true,                              color: "#1c3326", colorTo: "#15803d", icon: "👳" },
  { id: "p16", name: "مصر أرض المجددين",   category: "dawah",                                                                                color: "#1e3a5f", colorTo: "#1e40af", icon: "🇪🇬" },
  { id: "p17", name: "البناء الإيماني",    category: "dawah",                                                                                color: "#422006", colorTo: "#d97706", icon: "🏗️" },
  { id: "p18", name: "الطريق إلى الله",    category: "dawah",                                                                                color: "#0c0a09", colorTo: "#1c1917", icon: "🌄" },
  { id: "p19", name: "كنوز السنة",         category: "dawah",                                                                                color: "#3b0764", colorTo: "#7c3aed", icon: "💎" },
  { id: "p20", name: "رسالة إلى الله",     category: "dawah",                                                                                color: "#0c4a6e", colorTo: "#0284c7", icon: "📩" },

  { id: "p21", name: "اسأل مع دعاء",       category: "fatwa", featured: true,                                                                color: "#422006", colorTo: "#b45309", icon: "❓" },
  { id: "p22", name: "فتاوى على الهواء",   category: "fatwa",                                                                                color: "#1a1a2e", colorTo: "#16213e", icon: "📡" },
  { id: "p23", name: "الجواب الكافي",       category: "fatwa",                                                                                color: "#14532d", colorTo: "#15803d", icon: "✅" },
  { id: "p24", name: "الدين والحياة",       category: "fatwa",                                                                                color: "#1e3a8a", colorTo: "#2563eb", icon: "⚖️" },
  { id: "p25", name: "فاسألوا أهل الذكر",  category: "fatwa",                                                                                color: "#3b0764", colorTo: "#6d28d9", icon: "🧑‍🏫" },
  { id: "p26", name: "بين السائل والفقيه",  category: "fatwa",                                                                                color: "#0c4a6e", colorTo: "#0369a1", icon: "🗣️" },
  { id: "p27", name: "مع الناس",            category: "fatwa",                                                                                color: "#166534", colorTo: "#16a34a", icon: "👥" },
  { id: "p28", name: "فتاوى رمضان",         category: "fatwa",                                                                                color: "#78350f", colorTo: "#d97706", icon: "🌙" },
  { id: "p29", name: "نور الفتاوى",         category: "fatwa",                                                                                color: "#0c0a09", colorTo: "#44403c", icon: "🕯️" },
  { id: "p30", name: "الشريعة والحياة",     category: "fatwa",                                                                                color: "#1e3a5f", colorTo: "#1e40af", icon: "📋" },

  { id: "p31", name: "قصص الأنبياء",        category: "stories", featured: true, hot: true, badge: "خالد",                                   color: "#064e3b", colorTo: "#065f46", icon: "📚" },
  { id: "p32", name: "السيرة النبوية",       category: "stories", featured: true,            badge: "مميز",                                   color: "#1c1917", colorTo: "#44403c", icon: "🌹" },
  { id: "p33", name: "رجال حول الرسول",     category: "stories",                                                                              color: "#422006", colorTo: "#b45309", icon: "⚔️" },
  { id: "p34", name: "عمر (وثائقي درامي)",  category: "stories", featured: true, hot: true, badge: "ملحمي",                                   color: "#1a1a2e", colorTo: "#16213e", icon: "🎬" },
  { id: "p35", name: "حياة الصحابة",        category: "stories",                                                                              color: "#14532d", colorTo: "#166534", icon: "🌟" },
  { id: "p36", name: "قصص القرآن",          category: "stories",                                                                              color: "#0c4a6e", colorTo: "#0369a1", icon: "📖" },
  { id: "p37", name: "ثم اهتديت",           category: "stories",                                                                              color: "#3b0764", colorTo: "#7c3aed", icon: "🕊️" },
  { id: "p38", name: "أعلام الإسلام",       category: "stories",                                                                              color: "#1e3a8a", colorTo: "#1d4ed8", icon: "🏆" },
  { id: "p39", name: "مساجد من التاريخ",    category: "stories",                                                                              color: "#166534", colorTo: "#15803d", icon: "🕌" },
  { id: "p40", name: "مساجد الشرقية",       category: "stories",                                                                              color: "#422006", colorTo: "#92400e", icon: "🏛️" },

  { id: "p41", name: "نور على الدرب",       host: "ابن باز & ابن عثيمين",  category: "radio", featured: true, hot: true, badge: "أسطوري",   color: "#0c4a6e", colorTo: "#0369a1", icon: "📻" },
  { id: "p42", name: "حديث الصباح",         category: "radio",                                                                                color: "#78350f", colorTo: "#f59e0b", icon: "🌅" },
  { id: "p43", name: "قطوف إيمانية",        category: "radio",                                                                                color: "#14532d", colorTo: "#16a34a", icon: "🌾" },
  { id: "p44", name: "خواطر إسلامية",       category: "radio",                                                                                color: "#1e3a5f", colorTo: "#1e40af", icon: "💭" },
  { id: "p45", name: "دين ودنيا",           category: "radio",                                                                                color: "#1c1917", colorTo: "#292524", icon: "🌍" },
  { id: "p46", name: "رسالة الإسلام",       category: "radio",                                                                                color: "#064e3b", colorTo: "#065f46", icon: "📨" },
  { id: "p47", name: "التلاوة والتفسير",    category: "radio",                                                                                color: "#422006", colorTo: "#b45309", icon: "🎙️" },
  { id: "p48", name: "فقه الحياة",          category: "radio",                                                                                color: "#3b0764", colorTo: "#6d28d9", icon: "🔬" },
  { id: "p49", name: "مع القرآن الكريم",    category: "radio",                                                                                color: "#166534", colorTo: "#15803d", icon: "📿" },
  { id: "p50", name: "دقائق إيمانية",       category: "radio",                                                                                color: "#0c0a09", colorTo: "#1c1917", icon: "⏱️" },
];

export const FEATURED_PROGRAMS = PROGRAMS.filter((p) => p.featured);

export const LIVE_RADIO_STATIONS: RadioStation[] = [
  {
    id: "radio-cairo",
    name: "إذاعة القرآن من القاهرة",
    url: "https://stream.radiojar.com/8s5u5tpdtwzuv.mp3",
    logo: "https://play-lh.googleusercontent.com/2JbGhJox4i9yljgqANaAHBIv_7z1KekZ5PS9bZxxU1jsPktIHAJcX-VvVunEqUtN6Q5BPu8vCpcEBZXHais3mw=w240-h480-rw",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-saudi",
    name: "إذاعة القرآن من السعودية",
    url: "https://stream.radiojar.com/0tpy1h0kxtzuv.mp3",
    logo: "https://i1.sndcdn.com/avatars-EbeDM9V1tVVw7gAE-yibBcg-t1080x1080.jpg",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-zayed",
    name: "إذاعة زايد للقرآن الكريم",
    url: "https://zayedquran.gov.ae/stream.php",
    logo: "https://radio.qassimy.com/wp-content/uploads/2023/03/%D8%A7%D8%B0%D8%A7%D8%B9%D8%A9-%D8%B2%D8%A7%D9%8A%D8%AF-%D9%84%D9%84%D9%82%D8%B1%D8%A7%D9%86-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85-%D8%A7%D9%84%D9%81%D8%AC%D9%8A%D8%B1%D8%A9-%D8%A8%D8%AB-%D9%85%D8%A8%D8%A7%D8%B4%D8%B1.jpg",
    color: "#d97706",
    colorTo: "#f59e0b",
  },
  {
    id: "radio-shaarawy",
    name: "تفسير الشعراوي",
    url: "https://backup.qurango.net/radio/gareeb-quran",
    color: "#7c3aed",
    colorTo: "#a78bfa",
  },
  {
    id: "radio-maher",
    name: "ماهر المعيقلي",
    url: "https://backup.qurango.net/radio/maher",
    color: "#059669",
    colorTo: "#10b981",
  },
  {
    id: "radio-abdulbasit",
    name: "عبدالباسط عبد الصمد",
    url: "https://backup.qurango.net/radio/abdulbasit_abdulsamad_mojawwad",
    color: "#d97706",
    colorTo: "#f59e0b",
  },
];

export const PODCAST_CATEGORIES: PodcastCategory[] = [
  {
    id: "ala-khuta",
    title: "علي خطي الرسول",
    description: "نتتبع خطوات رسول الله ﷺ ونحقق الاتباع ونسير على الطريق.",
    color: "#064e3b",
    colorTo: "#065f46",
    episodes: [
      { id: "yom-alfrkan", title: "يوم الفرقان", description: "يوم غزوة بدر الكبرى", mediaUrl: "https://islamicaudio.net/assets/media/yom-alfrkan866.mp3" },
      { id: "hkm-alamyn", title: "حكم الأمين", description: "حكم الأمين ﷺ حجة على كفار قريش", mediaUrl: "https://islamicaudio.net/assets/media/hkm-alamyn871.mp3" },
      { id: "fth-mka", title: "فتح مكة", description: "تحقيق لوعد الله لنبيِّه ﷺ", mediaUrl: "https://islamicaudio.net/assets/media/fth-mk868.mp3" },
      { id: "slh-alhdyby", title: "صلح الحديبية", description: "الفتح المبين", mediaUrl: "https://islamicaudio.net/assets/media/slh-alhdyby874.mp3" },
      { id: "mhajron-oansar", title: "مهاجرون وأنصار", description: "قصة فريدة في تاريخ البشر", mediaUrl: "https://islamicaudio.net/assets/media/mhajron-oansar864.mp3" },
      { id: "ghrb-aleyman", title: "غربة الإيمان", mediaUrl: "https://islamicaudio.net/assets/media/ghrb-aleyman869.mp3" },
      { id: "alrfyk-alaaal", title: "الرفيق الأعلى", mediaUrl: "https://islamicaudio.net/assets/media/alrfyk-alaaal861.mp3" },
      { id: "alhjr", title: "الهجرة", mediaUrl: "https://islamicaudio.net/assets/media/alhjr862.mp3" },
      { id: "bd-alohy", title: "بدء الوحي", mediaUrl: "https://islamicaudio.net/assets/media/bd-alohy863.mp3" },
      { id: "maark-ahd", title: "معركة أحد", mediaUrl: "https://islamicaudio.net/assets/media/maark-ahd865.mp3" },
    ],
  },
  {
    id: "shrfat",
    title: "شرفات",
    description: "بودكاست من المستقبل، يبثُّ فينا الأمل.",
    color: "#1e3a5f",
    colorTo: "#1e40af",
    episodes: [
      { id: "fy-lj-albhr", title: "في لج البحر", mediaUrl: "https://islamicaudio.net/assets/media/13-fy-lj-albhr-aaaly-aldk849.mp3" },
      { id: "slaty-alaol", title: "صلاتي الأولى", mediaUrl: "https://islamicaudio.net/assets/media/02-slaty-alaol-aaaly-aldk858.mp3" },
      { id: "ahthr-theb", title: "احذر ذئب اللحظة المناسبة", mediaUrl: "https://islamicaudio.net/assets/media/12-ahthr-theb-allhth-almnasb-aaaly-aldk848.mp3" },
      { id: "hl-jrbt", title: "هل جربت هذه التجارة", mediaUrl: "https://islamicaudio.net/assets/media/10-hl-jrbt-hthh-altjar-aaaly-aldk851.mp3" },
      { id: "htha-alsaek", title: "هذا السائق", mediaUrl: "https://islamicaudio.net/assets/media/07-htha-alsaek-aaaly-aldk853.mp3" },
      { id: "kraan-alfjr", title: "قرآن الفجر", mediaUrl: "https://islamicaudio.net/assets/media/06-kraan-alfjr-aaaly-aldk856.mp3" },
      { id: "syarty-alkdym", title: "سيارتي القديمة وشيخي الراوي", mediaUrl: "https://islamicaudio.net/assets/media/01-syarty-alkdym-oshykhy-alraoy-aaaly-aldk859.mp3" },
    ],
  },
  {
    id: "mtka",
    title: "مُتكأ",
    description: "بودكاست يحكي قصص أعلام النبلاء.",
    color: "#0c4a6e",
    colorTo: "#0369a1",
    episodes: [
      { id: "abn-aljozy", title: "ابن الجوزي", mediaUrl: "https://islamicaudio.net/assets/media/08-abn-aljozy-aaaly-aldk839.mp3" },
      { id: "alkady-shryh", title: "القاضي شريح", mediaUrl: "https://islamicaudio.net/assets/media/16-alkady-shryh-aaaly-aldk829.mp3" },
      { id: "alnooy", title: "النووي", mediaUrl: "https://islamicaudio.net/assets/media/09-alnooy-aaaly-aldk836.mp3" },
      { id: "albkhary", title: "البخاري", mediaUrl: "https://islamicaudio.net/assets/media/11-albkhary-aaaly-aldk834.mp3" },
      { id: "alshafaay", title: "الإمام الشافعي", mediaUrl: "https://islamicaudio.net/assets/media/06-alamam-alshafaay-aaaly-aldk838.mp3" },
      { id: "ahmd-bn-hnyl", title: "الإمام أحمد بن حنبل", mediaUrl: "https://islamicaudio.net/assets/media/12-ahmd-bn-hnyl-aaaly-aldk833.mp3" },
    ],
  },
];
